Update attachments.cds in test folder
Changing { sap.attachments.Attachments } to { Attachments } due to this error  CDS compilation failed (@sap/cds-compiler v5.8.2)
    db/attachments.cds:3:44-65: Error: Can't find package module ‘@cap-js/attachments’